{
  "contest": 154,
  "handle": "Aymen0909",
  "address": "0xbea9a04e1b82a3f6ad01ea8f5b43622f95f3f353",
  "risk": "3",
  "title": "ERROR IN UPDATING  **_checkpoint** IN THE **increaseUnlockTime** FUNCTION",
  "issueId": 217,
  "issueUrl": "https://github.com/code-423n4/2022-08-fiatdao-findings/issues/217"
}